# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\"\x15\n\x05\x41rray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\"$\n\x08GameData\x12\x18\n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x06.Array\"%\n\nGameOutput\x12\x17\n\x07outputs\x18\x01 \x03(\x0b\x32\x06.Array\"^\n\x06Result\x12\x0b\n\x03pid\x18\x01 \x01(\x05\x12\x0b\n\x03res\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\x02\x12\x0e\n\x06memory\x18\x04 \x01(\x02\x12\x0e\n\x06\x65nergy\x18\x05 \x01(\x02\x12\x0c\n\x04size\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ARRAY']._serialized_start=14
  _globals['_ARRAY']._serialized_end=35
  _globals['_GAMEDATA']._serialized_start=37
  _globals['_GAMEDATA']._serialized_end=73
  _globals['_GAMEOUTPUT']._serialized_start=75
  _globals['_GAMEOUTPUT']._serialized_end=112
  _globals['_RESULT']._serialized_start=114
  _globals['_RESULT']._serialized_end=208
# @@protoc_insertion_point(module_scope)
